---
sudo: required
dist: focal
language: python
env:
 - LINT=1
 - IMAGE="ubuntu:trusty"
 - IMAGE="ubuntu:xenial"
 - IMAGE="ubuntu:bionic"
 - IMAGE="ubuntu:focal"
 - IMAGE="images:centos/6/cloud"
 - IMAGE="images:centos/7/cloud"
 - IMAGE="images:centos/8/cloud"
script:
 - if [ ! -z ${LINT} ]; then echo "Hello, world!"; fi
# setup dependencies here to save time on simpler test environments
# wait for lxd socket to be ready after snap installation
# change permissions on lxd socket to allow travis user access
# (^^ this is a throw-away CI environment, do not do this at home)
 - if [ ! -z ${IMAGE} ]; then
      sudo lxd init --auto;
      sudo chmod 666 /var/snap/lxd/common/lxd/unix.socket;
   fi
 - if [ ! -z ${IMAGE} ]; then
      lxc launch ${IMAGE} mymachinecontainer;
      lxc exec mymachinecontainer -- sh -c "lsb_release -a || cat /etc/redhat-release";
   fi
